<li><a href="cloud">Iniciar Sesión</a></li>
<li><a href="./">Registrate</a></li>
<li><a href="poemas">Poemas</a></li>
<li><a href="noticias">Noticias</a></li>
<li><a href="eventos">Eventos</a></li>
<li><a href="comunidad-inkside">Comunidad</a></li>
<!-- <li><a href="#!">Articulos</a></li>
<li><a href="#!">Noticias</a></li>
<li><a href="#!">Eventos</a></li> -->
